local M = {}

local palette = require("vicarious.theme.palette")

local function set(group, values)
  vim.api.nvim_set_hl(0, group, values)
end

local function link(group, target)
  set(group, { link = target })
end

function M.apply()
  local p = palette

  local groups = {
    Normal = { fg = p.foreground, bg = p.background },
    NormalNC = { fg = p.foreground, bg = p.background },
    NormalFloat = { fg = p.foreground, bg = p.background_2 },
    FloatBorder = { fg = p.purple, bg = p.background_2 },
    FloatTitle = { fg = p.cyan, bg = p.background_2, bold = true },
    Cursor = { fg = p.background, bg = p.cursor },
    TermCursor = { fg = p.background, bg = p.terminal },
    CursorLine = { bg = p.background_2 },
    CursorColumn = { bg = p.background_2 },
    ColorColumn = { bg = p.surface },
    LineNr = { fg = p.muted },
    CursorLineNr = { fg = p.cyan, bold = true },
    SignColumn = { fg = p.muted, bg = p.background },
    FoldColumn = { fg = p.muted, bg = p.background },
    Folded = { fg = p.muted, bg = p.background_2 },
    WinSeparator = { fg = p.selection, bg = p.background },
    Visual = { bg = p.selection },
    Search = { fg = p.background, bg = p.yellow },
    IncSearch = { fg = p.background, bg = p.orange, bold = true },
    CurSearch = { fg = p.background, bg = p.magenta, bold = true },
    MatchParen = { fg = p.cyan, bg = p.selection, bold = true },
    Pmenu = { fg = p.foreground, bg = p.surface },
    PmenuSel = { fg = p.background, bg = p.cyan, bold = true },
    PmenuSbar = { bg = p.surface_2 },
    PmenuThumb = { bg = p.purple },
    WildMenu = { fg = p.background, bg = p.cyan },
    StatusLine = { fg = p.foreground, bg = p.surface },
    StatusLineNC = { fg = p.muted, bg = p.background_2 },
    WinBar = { fg = p.muted, bg = p.background },
    WinBarNC = { fg = p.comment, bg = p.background },
    TabLine = { fg = p.muted, bg = p.background_2 },
    TabLineSel = { fg = p.cyan, bg = p.surface, bold = true },
    TabLineFill = { bg = p.background },
    Directory = { fg = p.blue },
    Title = { fg = p.cyan, bold = true },
    ErrorMsg = { fg = p.red, bold = true },
    WarningMsg = { fg = p.yellow },
    MoreMsg = { fg = p.green },
    Question = { fg = p.cyan },
    NonText = { fg = p.surface_2 },
    EndOfBuffer = { fg = p.background },
    Whitespace = { fg = p.surface_2 },
    SpecialKey = { fg = p.selection },
    Conceal = { fg = p.muted },
    QuickFixLine = { fg = p.cyan, bg = p.background_2 },

    Comment = { fg = p.comment, italic = true },
    Constant = { fg = p.orange },
    String = { fg = p.green },
    Character = { fg = p.green },
    Number = { fg = p.orange },
    Boolean = { fg = p.orange, bold = true },
    Float = { fg = p.orange },
    Identifier = { fg = p.foreground },
    Function = { fg = p.blue },
    Statement = { fg = p.purple },
    Conditional = { fg = p.magenta },
    Repeat = { fg = p.magenta },
    Label = { fg = p.cyan },
    Operator = { fg = p.cyan },
    Keyword = { fg = p.purple, italic = true },
    Exception = { fg = p.red },
    PreProc = { fg = p.magenta },
    Include = { fg = p.purple },
    Define = { fg = p.magenta },
    Macro = { fg = p.magenta },
    Type = { fg = p.yellow },
    StorageClass = { fg = p.yellow },
    Structure = { fg = p.yellow },
    Typedef = { fg = p.yellow },
    Special = { fg = p.cyan },
    Underlined = { fg = p.blue, underline = true },
    Todo = { fg = p.background, bg = p.yellow, bold = true },
    Error = { fg = p.red },

    DiffAdd = { fg = p.green, bg = "#10261C" },
    DiffChange = { fg = p.blue, bg = "#132038" },
    DiffDelete = { fg = p.red, bg = "#2A111A" },
    DiffText = { fg = p.cyan, bg = "#20334B", bold = true },
    SpellBad = { undercurl = true, sp = p.red },
    SpellCap = { undercurl = true, sp = p.yellow },
    SpellLocal = { undercurl = true, sp = p.cyan },
    SpellRare = { undercurl = true, sp = p.purple },

    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red, bg = "#211019" },
    DiagnosticVirtualTextWarn = { fg = p.yellow, bg = "#211F12" },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = "#111B2D" },
    DiagnosticVirtualTextHint = { fg = p.cyan, bg = "#102124" },
    DiagnosticUnderlineError = { undercurl = true, sp = p.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },

    VicariousDashboardCircuit = { fg = p.selection },
    VicariousDashboardLogo = { fg = p.orange, bold = true },
    VicariousDashboardWolf = { fg = p.muted, bold = true },
    VicariousDashboardWolfEye = { fg = p.red, bold = true },
    VicariousDashboardWolfFang = { fg = p.cursor, bold = true },
    VicariousDashboardAccent = { fg = p.cyan, bold = true },
    VicariousDashboardTitle = { fg = p.purple, bold = true },
    VicariousDashboardMuted = { fg = p.muted },
    VicariousDashboardButton = { fg = p.foreground },
    VicariousDashboardKey = { fg = p.terminal, bold = true },
    VicariousDashboardFooter = { fg = p.comment, italic = true },
    VicariousStatusCommand = { fg = p.background, bg = p.purple, bold = true },
    VicariousStatusInput = { fg = p.background, bg = p.green, bold = true },
    VicariousStatusSelect = { fg = p.background, bg = p.magenta, bold = true },
    VicariousStatusOverwrite = { fg = p.background, bg = p.red, bold = true },
    VicariousStatusShell = { fg = p.background, bg = p.orange, bold = true },
    VicariousStatusInactive = { fg = p.muted, bg = p.surface },
    VicariousStatusSection = { fg = p.cyan, bg = p.surface },
    VicariousStatusFile = { fg = p.foreground, bg = p.surface },
    VicariousStatusGit = { fg = p.purple, bg = p.surface },
    VicariousStatusLsp = { fg = p.green, bg = p.surface },
    VicariousStatusStudy = { fg = p.background, bg = p.yellow, bold = true },
    VicariousWinbarPrefix = { fg = p.cyan, bg = p.background, bold = true },
    VicariousWinbarPath = { fg = p.muted, bg = p.background },
    VicariousWinbarModified = { fg = p.orange, bg = p.background, bold = true },
  }

  for group, values in pairs(groups) do
    set(group, values)
  end

  local links = {
    ["@comment"] = "Comment",
    ["@comment.todo"] = "Todo",
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Constant",
    ["@string"] = "String",
    ["@character"] = "Character",
    ["@number"] = "Number",
    ["@boolean"] = "Boolean",
    ["@function"] = "Function",
    ["@function.builtin"] = "Special",
    ["@function.call"] = "Function",
    ["@constructor"] = "Type",
    ["@keyword"] = "Keyword",
    ["@keyword.function"] = "Keyword",
    ["@keyword.return"] = "Keyword",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.repeat"] = "Repeat",
    ["@operator"] = "Operator",
    ["@type"] = "Type",
    ["@type.builtin"] = "Type",
    ["@variable"] = "Identifier",
    ["@variable.builtin"] = "Special",
    ["@variable.parameter"] = "Identifier",
    ["@property"] = "Identifier",
    ["@attribute"] = "PreProc",
    ["@punctuation.bracket"] = "Special",
    ["@punctuation.delimiter"] = "Special",
    ["@tag"] = "Special",
    ["@tag.attribute"] = "Identifier",
    ["@markup.heading"] = "Title",
    ["@markup.link"] = "Underlined",
    ["@markup.raw"] = "String",
  }

  for group, target in pairs(links) do
    link(group, target)
  end

  M.apply_integrations()
end

function M.apply_integrations()
  local p = palette
  local groups = {
    TelescopeNormal = { fg = p.foreground, bg = p.background_2 },
    TelescopeBorder = { fg = p.selection, bg = p.background_2 },
    TelescopeTitle = { fg = p.background, bg = p.purple, bold = true },
    TelescopePromptNormal = { fg = p.foreground, bg = p.surface },
    TelescopePromptBorder = { fg = p.cyan, bg = p.surface },
    TelescopePromptTitle = { fg = p.background, bg = p.cyan, bold = true },
    TelescopePromptPrefix = { fg = p.terminal, bg = p.surface },
    TelescopeSelection = { fg = p.foreground, bg = p.selection, bold = true },
    TelescopeSelectionCaret = { fg = p.magenta, bg = p.selection, bold = true },
    TelescopeMatching = { fg = p.terminal, bold = true },

    NeoTreeNormal = { fg = p.foreground, bg = p.background_2 },
    NeoTreeNormalNC = { fg = p.foreground, bg = p.background_2 },
    NeoTreeWinSeparator = { fg = p.selection, bg = p.background },
    NeoTreeDirectoryIcon = { fg = p.blue },
    NeoTreeDirectoryName = { fg = p.blue },
    NeoTreeRootName = { fg = p.cyan, bold = true },
    NeoTreeFileNameOpened = { fg = p.terminal, bold = true },
    NeoTreeGitAdded = { fg = p.green },
    NeoTreeGitModified = { fg = p.yellow },
    NeoTreeGitDeleted = { fg = p.red },
    NeoTreeIndentMarker = { fg = p.selection },
    NeoTreeTitleBar = { fg = p.background, bg = p.purple, bold = true },

    BufferLineFill = { bg = p.background },
    BufferLineBackground = { fg = p.muted, bg = p.background_2 },
    BufferLineBufferSelected = { fg = p.foreground, bg = p.surface, bold = true },
    BufferLineBufferVisible = { fg = p.muted, bg = p.background_2 },
    BufferLineIndicatorSelected = { fg = p.cyan, bg = p.surface },
    BufferLineSeparator = { fg = p.background, bg = p.background_2 },
    BufferLineSeparatorSelected = { fg = p.background, bg = p.surface },
    BufferLineModified = { fg = p.orange, bg = p.background_2 },
    BufferLineModifiedSelected = { fg = p.orange, bg = p.surface },
    BufferLineOffsetSeparator = { fg = p.selection, bg = p.background_2 },

    GitSignsAdd = { fg = p.green },
    GitSignsChange = { fg = p.blue },
    GitSignsDelete = { fg = p.red },
    CmpItemAbbr = { fg = p.foreground },
    CmpItemAbbrMatch = { fg = p.cyan, bold = true },
    CmpItemAbbrDeprecated = { fg = p.muted, strikethrough = true },
    CmpItemKindFunction = { fg = p.blue },
    CmpItemKindMethod = { fg = p.blue },
    CmpItemKindVariable = { fg = p.magenta },
    CmpItemKindKeyword = { fg = p.purple },
    CmpItemKindClass = { fg = p.yellow },
    CmpItemKindSnippet = { fg = p.green },
    WhichKey = { fg = p.cyan },
    WhichKeyGroup = { fg = p.purple },
    WhichKeyDesc = { fg = p.foreground },
    WhichKeyBorder = { fg = p.selection },
    LazyButtonActive = { fg = p.background, bg = p.cyan, bold = true },
    LazyH1 = { fg = p.background, bg = p.purple, bold = true },
    MasonHeader = { fg = p.background, bg = p.purple, bold = true },
    MasonHighlight = { fg = p.cyan },
    DapBreakpoint = { fg = p.red },
    DapStopped = { fg = p.yellow, bg = "#211F12" },

    RenderMarkdownH1 = { fg = p.cyan, bold = true },
    RenderMarkdownH2 = { fg = p.purple, bold = true },
    RenderMarkdownH3 = { fg = p.blue, bold = true },
    RenderMarkdownH4 = { fg = p.magenta, bold = true },
    RenderMarkdownH5 = { fg = p.green, bold = true },
    RenderMarkdownH6 = { fg = p.yellow, bold = true },
    RenderMarkdownH1Bg = { fg = p.cyan, bg = "#102124", bold = true },
    RenderMarkdownH2Bg = { fg = p.purple, bg = "#1B142B", bold = true },
    RenderMarkdownH3Bg = { fg = p.blue, bg = "#111B2D", bold = true },
    RenderMarkdownH4Bg = { fg = p.magenta, bg = "#271225", bold = true },
    RenderMarkdownH5Bg = { fg = p.green, bg = "#10261C", bold = true },
    RenderMarkdownH6Bg = { fg = p.yellow, bg = "#211F12", bold = true },
    RenderMarkdownCode = { bg = p.background_2 },
    RenderMarkdownCodeInline = { fg = p.terminal, bg = p.surface },
    RenderMarkdownBullet = { fg = p.cyan, bold = true },
    RenderMarkdownDash = { fg = p.selection },
    RenderMarkdownChecked = { fg = p.green },
    RenderMarkdownUnchecked = { fg = p.muted },
    RenderMarkdownTodo = { fg = p.yellow },
    RenderMarkdownQuote1 = { fg = p.purple },
    RenderMarkdownQuote2 = { fg = p.blue },
    RenderMarkdownQuote3 = { fg = p.cyan },
    RenderMarkdownQuote4 = { fg = p.green },
    RenderMarkdownQuote5 = { fg = p.yellow },
    RenderMarkdownQuote6 = { fg = p.orange },
    RenderMarkdownTableHead = { fg = p.cyan, bold = true },
    RenderMarkdownTableRow = { fg = p.selection },
    RenderMarkdownLink = { fg = p.blue, underline = true },
    RenderMarkdownWikiLink = { fg = p.purple, underline = true },
    RenderMarkdownInlineHighlight = { fg = p.background, bg = p.yellow },

    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder = { fg = p.yellow },
    NotifyINFOBorder = { fg = p.blue },
    NotifyDEBUGBorder = { fg = p.muted },
    NotifyTRACEBorder = { fg = p.purple },
    NotifyERRORIcon = { fg = p.red },
    NotifyWARNIcon = { fg = p.yellow },
    NotifyINFOIcon = { fg = p.cyan },
    NotifyDEBUGIcon = { fg = p.muted },
    NotifyTRACEIcon = { fg = p.purple },
    NotifyERRORTitle = { fg = p.red, bold = true },
    NotifyWARNTitle = { fg = p.yellow, bold = true },
    NotifyINFOTitle = { fg = p.cyan, bold = true },
    NotifyDEBUGTitle = { fg = p.muted, bold = true },
    NotifyTRACETitle = { fg = p.purple, bold = true },
  }

  for group, values in pairs(groups) do
    set(group, values)
  end
end

return M
